/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Logo: THREE.Mesh;
    wallDecor: THREE.Mesh;
    Durags: THREE.Mesh;
    Kiosk: THREE.Mesh;
    Speakers: THREE.Mesh;
    Rug: THREE.Mesh;
    topCeiling: THREE.Mesh;
    Walls: THREE.Mesh;
  };
  materials: {
    ["Cube.1"]: THREE.MeshStandardMaterial;
    ["vp logo wall"]: THREE.MeshStandardMaterial;
    ["durag skull"]: THREE.MeshStandardMaterial;
    Box008: THREE.MeshStandardMaterial;
    speaker: THREE.MeshStandardMaterial;
    Cylinder: THREE.MeshStandardMaterial;
    topCeiling: THREE.MeshStandardMaterial;
    walls: THREE.MeshStandardMaterial;
  };
};

const FILEURL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/test_16-1612513316/00.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILEURL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group scale={[3, 3, 3]}>
        <mesh
          material={materials["Cube.1"]}
          geometry={nodes.Logo.geometry}
          name="Logo"
          rotation={[0, 0, 0]}
        />
        <mesh
          material={materials["vp logo wall"]}
          geometry={nodes.wallDecor.geometry}
          name="wallDecor"
        />
        <mesh
          material={materials["durag skull"]}
          geometry={nodes.Durags.geometry}
          name="Durags"
          rotation={[0, 0, 0]}
        />
        <mesh
          material={materials.Box008}
          geometry={nodes.Kiosk.geometry}
          name="Kiosk"
        />
        <mesh
          material={materials.speaker}
          geometry={nodes.Speakers.geometry}
          name="Speakers"
          rotation={[0, 0, 0]}
        />
        <mesh
          material={materials.Cylinder}
          geometry={nodes.Rug.geometry}
          name="Rug"
        />
        <mesh
          material={materials.topCeiling}
          geometry={nodes.topCeiling.geometry}
          name="topCeiling"
        />
        <mesh
          material={materials.walls}
          geometry={nodes.Walls.geometry}
          name="Walls"
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILEURL);
