/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    collider: THREE.Mesh;
    mesh: THREE.Mesh;
  };
  materials: THREE.MeshStandardMaterial;
};

const FILEURL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/test_17-1612530204/outdoor_02.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILEURL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          material={nodes.collider.material}
          geometry={nodes.collider.geometry}
          name="collider"
        />
        <mesh
          material={nodes.mesh.material}
          geometry={nodes.mesh.geometry}
          name="mesh"
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILEURL);
