/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    floor: THREE.Mesh;
    walls: THREE.Mesh;
    celling: THREE.Mesh;
    glass: THREE.Mesh;
    skylight: THREE.Mesh;
    windows: THREE.Mesh;
    beams: THREE.Mesh;
    concrete_walls: THREE.Mesh;
    doors: THREE.Mesh;
    ventmat: THREE.Mesh;
  };
  materials: {
    ["floor.mat"]: THREE.MeshStandardMaterial;
    ["walls.mat"]: THREE.MeshStandardMaterial;
    ["ceiling.mat"]: THREE.MeshStandardMaterial;
    ["glass.mat"]: THREE.MeshStandardMaterial;
    ["skylight.mat"]: THREE.MeshStandardMaterial;
    ["windows.mat"]: THREE.MeshStandardMaterial;
    ["beams.mat"]: THREE.MeshStandardMaterial;
    ["concrete_walls.mat"]: THREE.MeshStandardMaterial;
    ["doors.mat"]: THREE.MeshStandardMaterial;
    ["vent.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILEURL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/test_00-1607507020/structure_00.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILEURL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group position-y={0} position-x={0} position-z={0} scale={[20, 20, 20]}>
        <mesh
          material={materials["floor.mat"]}
          geometry={nodes.floor.geometry}
          name="floor"
        />
        <mesh
          material={materials["walls.mat"]}
          geometry={nodes.walls.geometry}
          name="walls"
        />
        <mesh
          material={materials["ceiling.mat"]}
          geometry={nodes.celling.geometry}
          name="celling"
        />
        <mesh
          material={materials["glass.mat"]}
          geometry={nodes.glass.geometry}
          name="glass"
        />
        <mesh
          material={materials["skylight.mat"]}
          geometry={nodes.skylight.geometry}
          name="skylight"
        />
        <mesh
          material={materials["windows.mat"]}
          geometry={nodes.windows.geometry}
          name="windows"
        />
        <mesh
          material={materials["beams.mat"]}
          geometry={nodes.beams.geometry}
          name="beams"
        />
        <mesh
          material={materials["concrete_walls.mat"]}
          geometry={nodes.concrete_walls.geometry}
          name="concrete_walls"
        />
        <mesh
          material={materials["doors.mat"]}
          geometry={nodes.doors.geometry}
          name="doors"
        />
        <mesh
          material={materials["vent.mat"]}
          geometry={nodes.ventmat.geometry}
          name="ventmat"
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILEURL);
