/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    PORTFOLIO: THREE.Mesh;
  };
  materials: {
    ["PORTFOLIO.MAT"]: THREE.MeshStandardMaterial;
  };
};

const FILEURL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/test_00-1607137473/test.bake.04.BAKESCONNECTED.4KGLTF.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILEURL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          material={materials["PORTFOLIO.MAT"]}
          geometry={nodes.PORTFOLIO.geometry}
          name="PORTFOLIO"
          position={[0.482, 4.233, -5.211]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILEURL);
